def sort_dicts_ai(data, key):
    """
    AI-suggested implementation to sort list of dictionaries by key
    Generated by GitHub Copilot
    """
    return sorted(data, key=lambda x: x[key])

# Test data
test_data = [
    {'name': 'John', 'age': 25},
    {'name': 'Alice', 'age': 30},
    {'name': 'Bob', 'age': 20}
]

# Test the function
sorted_data = sort_dicts_ai(test_data.copy(), 'age')
print("AI sort result:", sorted_data)